---
- hosts: hive
  gather_facts: false
  ignore_errors: true
  roles:
    - vhw
  vars_files:
    - "{{ inventory_dir }}/vhw_credentials.yml"
    - "{{ inventory_dir }}/vhw_config.yml"
  tags:
    - vhw
  vars:
    create: "{{ create_vms }}"

- hosts: all
  gather_facts: false
  become: yes
  roles:
    - common
  vars_files:
    - "{{ inventory_dir }}/linux.yml"