---
- hosts: hive
  gather_facts: false
  ignore_errors: true
  roles:
    - vhw
  vars_files:
    - "{{ inventory_dir }}/vhw_credentials.yml"
    - "{{ inventory_dir }}/vhw_config.yml"
  tags:
    - vhw
  vars:
    create: "{{ create_vms }}"

- hosts: hive
  gather_facts: true
  become: yes
  roles:
    #- common
    - docker
  vars_files:
    - "{{ inventory_dir }}/linux.yml"
    - "{{ inventory_dir }}/docker.yml"