- name: "Check choosen shell is exist"
  stat:
    path: "{{ user.shell }}"
  register: shell_bin

- name: "Create users"
  user:
    name: "{{ user.login }}"
    shell: "{{ user.shell if shell_bin.stat.exists else '/bin/bash' }}"
    state: present
  register: user_data

- name: "Create public keys"
  template:
    src: authorized_keys.j2
    dest: "{{ user_data.home }}/.ssh/authorized_keys"
    mode: 0644
    owner: "{{ user.login }}"
    group: "{{ user.login }}"
  when: user.id_pub is defined

- block:
  - name: "Copying configs | create dirs"
    file:
      state: directory
      path: "{{ user_data.home }}/{{ item.dst | dirname }}"
      owner: "{{ user.login }}"
      group: "{{ user.login }}"
      recurse: true
    loop: "{{ user.config }}"

  - name: "Copying configs | downloading"
    get_url:
      url: "{{ item.src }}"
      dest: "{{ user_data.home }}/{{ item.dst }}"
      owner: "{{ user.login }}"
      group: "{{ user.login }}"
    loop: "{{ user.config }}"
  when: user.config is defined